# Generated by Django 4.2.5 on 2023-09-21 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(max_length=100)),
                ('pmid', models.IntegerField()),
                ('abtract', models.TextField(max_length=100)),
                ('full_text_link', models.TextField(max_length=100)),
                ('keywords', models.TextField(max_length=100)),
            ],
        ),
        migrations.DeleteModel(
            name='StudentModel',
        ),
    ]
