# Generated by Django 4.2.5 on 2023-09-22 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_page_delete_studentmodel'),
    ]

    operations = [
        migrations.RenameField(
            model_name='page',
            old_name='abtract',
            new_name='abstract',
        ),
    ]
